name: Artifacts (Package)

on: [push, pull_request, workflow_dispatch]

jobs:
  build-artifacts:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup problem matcher
      uses: Joshua-Ashton/gcc-problem-matcher@v1

    - name: Build release
      id: build-release
      uses: Joshua-Ashton/arch-mingw-github-action@v8
      with:
        command: |
          export VERSION_NAME="${GITHUB_REF##*/}-${GITHUB_SHA##*/}"
          ./package-release.sh ${VERSION_NAME} build --no-package
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

    - name: Create Tar
      run: |
        tar -czvf dxvk-${{ env.VERSION_NAME }}.tar.gz build/dxvk-${{ env.VERSION_NAME }}/

    - name: "Create Release"
      uses: softprops/action-gh-release@v2
      with:
        name: "dxvk-${{ env.VERSION_NAME }}"
        tag_name: ${{ env.VERSION_NAME }}
        files: dxvk-${{ env.VERSION_NAME }}.tar.gz
    
